name: ğŸ› ï¸ æ„å»º test

on:
  workflow_dispatch:

env:
  KERNEL_WORKSPACE: ${{ github.workspace }}/kernel_workspace
  release: "true"  # é»˜è®¤è®¾ç½®ä¸º trueï¼Œè¡¨ç¤ºéœ€è¦å‘å¸ƒ
  REPOS_JSON: "repos.oneplus_11.json"  # åŠ¨æ€æŒ‡å®šçš„ JSON æ–‡ä»¶è·¯å¾„

jobs:
  parse-config:
    name: "ğŸ“– è§£æé…ç½®æ–‡ä»¶"
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.parse.outputs.repo }}
    steps:
      - name: "ğŸ“š æ£€å‡ºä»£ç "
        uses: actions/checkout@v3

      - name: "ğŸ“ è§£ææŒ‡å®šçš„ JSON æ–‡ä»¶"
        id: parse
        run: |
          echo "repo<<EOF" >> $GITHUB_OUTPUT
          jq '.[]' ${{ env.REPOS_JSON }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  build-kernel:
    name: "ğŸ› ï¸ æ„å»º KernelSU Next SUSFS"
    runs-on: ubuntu-latest
    needs: parse-config
    steps:
      - name: "ğŸ› ï¸ æ¨¡æ‹Ÿç”Ÿæˆæ„å»ºäº§ç‰©"
        run: |
          mkdir -p $KERNEL_WORKSPACE && cd $KERNEL_WORKSPACE
          cd $KERNEL_WORKSPACE
          echo "This is a test file" > ./testfile.txt

      - name: "ğŸ› ï¸ åˆ›å»º AnyKernel3"
        run: |
          git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
          rm -rf ./AnyKernel3/.git
          cp $KERNEL_WORKSPACE/testfile.txt ./AnyKernel3/

      - name: "ğŸ“¤ æ‰“åŒ…"
        id: package
        env:
          zipname: "AnyKernel3_KernelSU_Next_${{ github.run_number }}_test"
        run: |
          cd AnyKernel3/
          zip -q -r "${{ env.zipname }}.zip" *

      - name: "ğŸ“¤ ä¸Šä¼ æ„å»ºäº§ç‰©"
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3_KernelSU_Next_${{ github.run_number }}_test
          path: "./AnyKernel3/*"

      - name: "ğŸ” æ£€æŸ¥ AnyKernel3 ç›®å½•å†…å®¹"
        run: |
          ls -la $KERNEL_WORKSPACE/
          ls -la ${{ github.workspace }}/
          ls -la ${{ github.workspace }}/AnyKernel3/
      # - name: "ğŸ§§ åˆ›å»º GitHub Release"
      #   uses: softprops/action-gh-release@v2
      #   if: ${{ env.release == 'true' }}
      #   with:
      #     tag_name: "KernelSU-Next-SUSFS-Test-${{ github.run_number }}"
      #     name: "KernelSU Next SUSFS å†…æ ¸æµ‹è¯• v${{ github.run_number }}"
      #     generate_release_notes: true
      #     files: "${{ github.workspace }}/AnyKernel3_KernelSU_Next_${{ github.run_number }}_test.zip"